<?php
// Check if the form has been submitted
if (isset($_POST['user_ID'])) {
     // Get the form data
     $return = $_POST['return'];
     $alert = $_POST['alert'];
     $user_ID = $_POST['user_ID'];
     $lesson_activity_number = $_POST['lesson_activity_number'];
     $url = $_POST['url'];

     include "conn.php";

     // Check for a successful connection
     if (!$conn) {
          die("Connection failed: " . mysqli_connect_error());
     }

     // Create a prepared statement with placeholders
     $query = "INSERT INTO lesson_tutorial_url (`user_ID`, `lesson_activity_number`, `lesson_tutorial_url`)
              VALUES (?, ?, ?)
              ON DUPLICATE KEY UPDATE `lesson_tutorial_url` = ?";

     // Prepare the statement
     $stmt = mysqli_prepare($conn, $query);

     // Bind parameters to the prepared statement
     mysqli_stmt_bind_param($stmt, "iiss", $user_ID, $lesson_activity_number, $url, $url);

     // Execute the prepared statement
     if (mysqli_stmt_execute($stmt)) {
          session_start();  // Make sure to start the session
          $_SESSION['alertThis'] = $alert;
          mysqli_stmt_close($stmt);
          mysqli_close($conn);

          header("Location: " . $return);
          exit();
     } else {
          echo "Error: " . mysqli_error($conn);
     }

     // Close the prepared statement and database connection
     mysqli_stmt_close($stmt);
     mysqli_close($conn);
}
?>

<!-- create table  -->
<!-- CREATE TABLE `english_adventure`.`lesson_tutorial_url` (`lesson_tutorial_ID` INT(255) NOT NULL AUTO_INCREMENT , `user_ID` INT(255) NOT NULL , `lesson_tutorial_url` TEXT NOT NULL , `lesson_activity_number` INT(255) NOT NULL , `date_added` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `date_update` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL , PRIMARY KEY (`lesson_tutorial_ID`)) ENGINE = InnoDB; ALTER TABLE `lesson_tutorial_url` ADD UNIQUE(`lesson_activity_number`);-->

<!-- CREATE TABLE word_sound_activity (
word_sound_activity_ID INT AUTO_INCREMENT PRIMARY KEY,
user_ID INT NOT NULL,
lesson_activity_number INT NOT NULL UNIQUE,
l11_easy_word_1 TEXT,
l11_easy_word_2 TEXT,
l11_easy_word_3 TEXT,
l11_easy_word_4 TEXT,
l11_easy_word_5 TEXT,
l11_easy_word_6 TEXT,
l11_easy_word_7 TEXT,
l11_easy_word_8 TEXT,
l11_easy_word_9 TEXT,
l11_easy_word_10 TEXT,
l11_easy_word_11 TEXT,
l11_easy_word_12 TEXT,
l11_easy_word_13 TEXT,
l11_easy_word_14 TEXT,
l11_easy_word_15 TEXT,
l11_easy_word_1_status ENUM('correct', 'wrong'),
l11_easy_word_2_status ENUM('correct', 'wrong'),
l11_easy_word_3_status ENUM('correct', 'wrong'),
l11_easy_word_4_status ENUM('correct', 'wrong'),
l11_easy_word_5_status ENUM('correct', 'wrong'),
l11_easy_word_6_status ENUM('correct', 'wrong'),
l11_easy_word_7_status ENUM('correct', 'wrong'),
l11_easy_word_8_status ENUM('correct', 'wrong'),
l11_easy_word_9_status ENUM('correct', 'wrong'),
l11_easy_word_10_status ENUM('correct', 'wrong'),
l11_easy_word_11_status ENUM('correct', 'wrong'),
l11_easy_word_12_status ENUM('correct', 'wrong'),
l11_easy_word_13_status ENUM('correct', 'wrong'),
l11_easy_word_14_status ENUM('correct', 'wrong'),
l11_easy_word_15_status ENUM('correct', 'wrong'),
l11_average_word_1 TEXT,
l11_average_word_2 TEXT,
l11_average_word_3 TEXT,
l11_average_word_4 TEXT,
l11_average_word_5 TEXT,
l11_average_word_6 TEXT,
l11_average_word_7 TEXT,
l11_average_word_8 TEXT,
l11_average_word_9 TEXT,
l11_average_word_10 TEXT,
l11_average_word_11 TEXT,
l11_average_word_12 TEXT,
l11_average_word_13 TEXT,
l11_average_word_14 TEXT,
l11_average_word_15 TEXT,
l11_average_word_1_status ENUM('correct', 'wrong'),
l11_average_word_2_status ENUM('correct', 'wrong'),
l11_average_word_3_status ENUM('correct', 'wrong'),
l11_average_word_4_status ENUM('correct', 'wrong'),
l11_average_word_5_status ENUM('correct', 'wrong'),
l11_average_word_6_status ENUM('correct', 'wrong'),
l11_average_word_7_status ENUM('correct', 'wrong'),
l11_average_word_8_status ENUM('correct', 'wrong'),
l11_average_word_9_status ENUM('correct', 'wrong'),
l11_average_word_10_status ENUM('correct', 'wrong'),
l11_average_word_11_status ENUM('correct', 'wrong'),
l11_average_word_12_status ENUM('correct', 'wrong'),
l11_average_word_13_status ENUM('correct', 'wrong'),
l11_average_word_14_status ENUM('correct', 'wrong'),
l11_average_word_15_status ENUM('correct', 'wrong'),
l11_difficult_word_1 TEXT,
l11_difficult_word_2 TEXT,
l11_difficult_word_3 TEXT,
l11_difficult_word_4 TEXT,
l11_difficult_word_5 TEXT,
l11_difficult_word_6 TEXT,
l11_difficult_word_7 TEXT,
l11_difficult_word_8 TEXT,
l11_difficult_word_9 TEXT,
l11_difficult_word_10 TEXT,
l11_difficult_word_11 TEXT,
l11_difficult_word_12 TEXT,
l11_difficult_word_13 TEXT,
l11_difficult_word_14 TEXT,
l11_difficult_word_15 TEXT,
l11_difficult_word_1_status ENUM('correct', 'wrong'),
l11_difficult_word_2_status ENUM('correct', 'wrong'),
l11_difficult_word_3_status ENUM('correct', 'wrong'),
l11_difficult_word_4_status ENUM('correct', 'wrong'),
l11_difficult_word_5_status ENUM('correct', 'wrong'),
l11_difficult_word_6_status ENUM('correct', 'wrong'),
l11_difficult_word_7_status ENUM('correct', 'wrong'),
l11_difficult_word_8_status ENUM('correct', 'wrong'),
l11_difficult_word_9_status ENUM('correct', 'wrong'),
l11_difficult_word_10_status ENUM('correct', 'wrong'),
l11_difficult_word_11_status ENUM('correct', 'wrong'),
l11_difficult_word_12_status ENUM('correct', 'wrong'),
l11_difficult_word_13_status ENUM('correct', 'wrong'),
l11_difficult_word_14_status ENUM('correct', 'wrong'),
l11_difficult_word_15_status ENUM('correct', 'wrong'),
l21_easy_word_1 TEXT,
l21_easy_word_2 TEXT,
l21_easy_word_3 TEXT,
l21_easy_word_4 TEXT,
l21_easy_word_5 TEXT,
l21_easy_word_6 TEXT,
l21_easy_word_7 TEXT,
l21_easy_word_8 TEXT,
l21_easy_word_9 TEXT,
l21_easy_word_10 TEXT,
l21_easy_word_11 TEXT,
l21_easy_word_12 TEXT,
l21_easy_word_13 TEXT,
l21_easy_word_14 TEXT,
l21_easy_word_15 TEXT,
l21_easy_word_1_status ENUM('correct', 'wrong'),
l21_easy_word_2_status ENUM('correct', 'wrong'),
l21_easy_word_3_status ENUM('correct', 'wrong'),
l21_easy_word_4_status ENUM('correct', 'wrong'),
l21_easy_word_5_status ENUM('correct', 'wrong'),
l21_easy_word_6_status ENUM('correct', 'wrong'),
l21_easy_word_7_status ENUM('correct', 'wrong'),
l21_easy_word_8_status ENUM('correct', 'wrong'),
l21_easy_word_9_status ENUM('correct', 'wrong'),
l21_easy_word_10_status ENUM('correct', 'wrong'),
l21_easy_word_11_status ENUM('correct', 'wrong'),
l21_easy_word_12_status ENUM('correct', 'wrong'),
l21_easy_word_13_status ENUM('correct', 'wrong'),
l21_easy_word_14_status ENUM('correct', 'wrong'),
l21_easy_word_15_status ENUM('correct', 'wrong'),
l21_average_word_1 TEXT,
l21_average_word_2 TEXT,
l21_average_word_3 TEXT,
l21_average_word_4 TEXT,
l21_average_word_5 TEXT,
l21_average_word_6 TEXT,
l21_average_word_7 TEXT,
l21_average_word_8 TEXT,
l21_average_word_9 TEXT,
l21_average_word_10 TEXT,
l21_average_word_11 TEXT,
l21_average_word_12 TEXT,
l21_average_word_13 TEXT,
l21_average_word_14 TEXT,
l21_average_word_15 TEXT,
l21_average_word_1_status ENUM('correct', 'wrong'),
l21_average_word_2_status ENUM('correct', 'wrong'),
l21_average_word_3_status ENUM('correct', 'wrong'),
l21_average_word_4_status ENUM('correct', 'wrong'),
l21_average_word_5_status ENUM('correct', 'wrong'),
l21_average_word_6_status ENUM('correct', 'wrong'),
l21_average_word_7_status ENUM('correct', 'wrong'),
l21_average_word_8_status ENUM('correct', 'wrong'),
l21_average_word_9_status ENUM('correct', 'wrong'),
l21_average_word_10_status ENUM('correct', 'wrong'),
l21_average_word_11_status ENUM('correct', 'wrong'),
l21_average_word_12_status ENUM('correct', 'wrong'),
l21_average_word_13_status ENUM('correct', 'wrong'),
l21_average_word_14_status ENUM('correct', 'wrong'),
l21_average_word_15_status ENUM('correct', 'wrong'),
l21_difficult_word_1 TEXT,
l21_difficult_word_2 TEXT,
l21_difficult_word_3 TEXT,
l21_difficult_word_4 TEXT,
l21_difficult_word_5 TEXT,
l21_difficult_word_6 TEXT,
l21_difficult_word_7 TEXT,
l21_difficult_word_8 TEXT,
l21_difficult_word_9 TEXT,
l21_difficult_word_10 TEXT,
l21_difficult_word_11 TEXT,
l21_difficult_word_12 TEXT,
l21_difficult_word_13 TEXT,
l21_difficult_word_14 TEXT,
l21_difficult_word_15 TEXT,
l21_difficult_word_1_status ENUM('correct', 'wrong'),
l21_difficult_word_2_status ENUM('correct', 'wrong'),
l21_difficult_word_3_status ENUM('correct', 'wrong'),
l21_difficult_word_4_status ENUM('correct', 'wrong'),
l21_difficult_word_5_status ENUM('correct', 'wrong'),
l21_difficult_word_6_status ENUM('correct', 'wrong'),
l21_difficult_word_7_status ENUM('correct', 'wrong'),
l21_difficult_word_8_status ENUM('correct', 'wrong'),
l21_difficult_word_9_status ENUM('correct', 'wrong'),
l21_difficult_word_10_status ENUM('correct', 'wrong'),
l21_difficult_word_11_status ENUM('correct', 'wrong'),
l21_difficult_word_12_status ENUM('correct', 'wrong'),
l21_difficult_word_13_status ENUM('correct', 'wrong'),
l21_difficult_word_14_status ENUM('correct', 'wrong'),
l21_difficult_word_15_status ENUM('correct', 'wrong'),
l31_easy_word_1 TEXT,
l31_easy_word_2 TEXT,
l31_easy_word_3 TEXT,
l31_easy_word_4 TEXT,
l31_easy_word_5 TEXT,
l31_easy_word_6 TEXT,
l31_easy_word_7 TEXT,
l31_easy_word_8 TEXT,
l31_easy_word_9 TEXT,
l31_easy_word_10 TEXT,
l31_easy_word_11 TEXT,
l31_easy_word_12 TEXT,
l31_easy_word_13 TEXT,
l31_easy_word_14 TEXT,
l31_easy_word_15 TEXT,
l31_easy_word_1_status ENUM('correct', 'wrong'),
l31_easy_word_2_status ENUM('correct', 'wrong'),
l31_easy_word_3_status ENUM('correct', 'wrong'),
l31_easy_word_4_status ENUM('correct', 'wrong'),
l31_easy_word_5_status ENUM('correct', 'wrong'),
l31_easy_word_6_status ENUM('correct', 'wrong'),
l31_easy_word_7_status ENUM('correct', 'wrong'),
l31_easy_word_8_status ENUM('correct', 'wrong'),
l31_easy_word_9_status ENUM('correct', 'wrong'),
l31_easy_word_10_status ENUM('correct', 'wrong'),
l31_easy_word_11_status ENUM('correct', 'wrong'),
l31_easy_word_12_status ENUM('correct', 'wrong'),
l31_easy_word_13_status ENUM('correct', 'wrong'),
l31_easy_word_14_status ENUM('correct', 'wrong'),
l31_easy_word_15_status ENUM('correct', 'wrong'),
l31_average_word_1 TEXT,
l31_average_word_2 TEXT,
l31_average_word_3 TEXT,
l31_average_word_4 TEXT,
l31_average_word_5 TEXT,
l31_average_word_6 TEXT,
l31_average_word_7 TEXT,
l31_average_word_8 TEXT,
l31_average_word_9 TEXT,
l31_average_word_10 TEXT,
l31_average_word_11 TEXT,
l31_average_word_12 TEXT,
l31_average_word_13 TEXT,
l31_average_word_14 TEXT,
l31_average_word_15 TEXT,
l31_average_word_1_status ENUM('correct', 'wrong'),
l31_average_word_2_status ENUM('correct', 'wrong'),
l31_average_word_3_status ENUM('correct', 'wrong'),
l31_average_word_4_status ENUM('correct', 'wrong'),
l31_average_word_5_status ENUM('correct', 'wrong'),
l31_average_word_6_status ENUM('correct', 'wrong'),
l31_average_word_7_status ENUM('correct', 'wrong'),
l31_average_word_8_status ENUM('correct', 'wrong'),
l31_average_word_9_status ENUM('correct', 'wrong'),
l31_average_word_10_status ENUM('correct', 'wrong'),
l31_average_word_11_status ENUM('correct', 'wrong'),
l31_average_word_12_status ENUM('correct', 'wrong'),
l31_average_word_13_status ENUM('correct', 'wrong'),
l31_average_word_14_status ENUM('correct', 'wrong'),
l31_average_word_15_status ENUM('correct', 'wrong'),
l31_difficult_word_1 TEXT,
l31_difficult_word_2 TEXT,
l31_difficult_word_3 TEXT,
l31_difficult_word_4 TEXT,
l31_difficult_word_5 TEXT,
l31_difficult_word_6 TEXT,
l31_difficult_word_7 TEXT,
l31_difficult_word_8 TEXT,
l31_difficult_word_9 TEXT,
l31_difficult_word_10 TEXT,
l31_difficult_word_11 TEXT,
l31_difficult_word_12 TEXT,
l31_difficult_word_13 TEXT,
l31_difficult_word_14 TEXT,
l31_difficult_word_15 TEXT,
l31_difficult_word_1_status ENUM('correct', 'wrong'),
l31_difficult_word_2_status ENUM('correct', 'wrong'),
l31_difficult_word_3_status ENUM('correct', 'wrong'),
l31_difficult_word_4_status ENUM('correct', 'wrong'),
l31_difficult_word_5_status ENUM('correct', 'wrong'),
l31_difficult_word_6_status ENUM('correct', 'wrong'),
l31_difficult_word_7_status ENUM('correct', 'wrong'),
l31_difficult_word_8_status ENUM('correct', 'wrong'),
l31_difficult_word_9_status ENUM('correct', 'wrong'),
l31_difficult_word_10_status ENUM('correct', 'wrong'),
l31_difficult_word_11_status ENUM('correct', 'wrong'),
l31_difficult_word_12_status ENUM('correct', 'wrong'),
l31_difficult_word_13_status ENUM('correct', 'wrong'),
l31_difficult_word_14_status ENUM('correct', 'wrong'),
l31_difficult_word_15_status ENUM('correct', 'wrong'),
date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); -->

<!-- CREATE TABLE recognizing_noun_activity (
recognizing_noun_activity_ID INT AUTO_INCREMENT PRIMARY KEY,
user_ID INT NOT NULL,
lesson_activity_number INT NOT NULL UNIQUE,
l12_easy_statement_1_image mediumblob NOT NULL,
l12_easy_statement_2_image mediumblob NOT NULL,
l12_easy_statement_3_image mediumblob NOT NULL,
l12_easy_statement_4_image mediumblob NOT NULL,
l12_easy_statement_5_image mediumblob NOT NULL,
l12_easy_statement_6_image mediumblob NOT NULL,
l12_easy_statement_7_image mediumblob NOT NULL,
l12_easy_statement_8_image mediumblob NOT NULL,
l12_average_statement_1_image mediumblob NOT NULL,
l12_average_statement_2_image mediumblob NOT NULL,
l12_average_statement_3_image mediumblob NOT NULL,
l12_average_statement_4_image mediumblob NOT NULL,
l12_average_statement_5_image mediumblob NOT NULL,
l12_average_statement_6_image mediumblob NOT NULL,
l12_average_statement_7_image mediumblob NOT NULL,
l12_average_statement_8_image mediumblob NOT NULL,
l12_difficult_statement_1_image mediumblob NOT NULL,
l12_difficult_statement_2_image mediumblob NOT NULL,
l12_difficult_statement_3_image mediumblob NOT NULL,
l12_difficult_statement_4_image mediumblob NOT NULL,
l12_difficult_statement_5_image mediumblob NOT NULL,
l12_difficult_statement_6_image mediumblob NOT NULL,
l12_difficult_statement_7_image mediumblob NOT NULL,
l12_difficult_statement_8_image mediumblob NOT NULL,
l12_easy_statement_1 TEXT,
l12_easy_statement_2 TEXT,
l12_easy_statement_3 TEXT,
l12_easy_statement_4 TEXT,
l12_easy_statement_5 TEXT,
l12_easy_statement_6 TEXT,
l12_easy_statement_7 TEXT,
l12_easy_statement_8 TEXT,
l12_average_statement_1 TEXT,
l12_average_statement_2 TEXT,
l12_average_statement_3 TEXT,
l12_average_statement_4 TEXT,
l12_average_statement_5 TEXT,
l12_average_statement_6 TEXT,
l12_average_statement_7 TEXT,
l12_average_statement_8 TEXT,
l12_difficult_statement_1 TEXT,
l12_difficult_statement_2 TEXT,
l12_difficult_statement_3 TEXT,
l12_difficult_statement_4 TEXT,
l12_difficult_statement_5 TEXT,
l12_difficult_statement_6 TEXT,
l12_difficult_statement_7 TEXT,
l12_difficult_statement_8 TEXT,
l12_easy_statement_1_correct_nouns TEXT,
l12_easy_statement_2_correct_nouns TEXT,
l12_easy_statement_3_correct_nouns TEXT,
l12_easy_statement_4_correct_nouns TEXT,
l12_easy_statement_5_correct_nouns TEXT,
l12_easy_statement_6_correct_nouns TEXT,
l12_easy_statement_7_correct_nouns TEXT,
l12_easy_statement_8_correct_nouns TEXT,
l12_average_statement_1_correct_nouns TEXT,
l12_average_statement_2_correct_nouns TEXT,
l12_average_statement_3_correct_nouns TEXT,
l12_average_statement_4_correct_nouns TEXT,
l12_average_statement_5_correct_nouns TEXT,
l12_average_statement_6_correct_nouns TEXT,
l12_average_statement_7_correct_nouns TEXT,
l12_average_statement_8_correct_nouns TEXT,
l12_difficult_statement_1_correct_nouns TEXT,
l12_difficult_statement_2_correct_nouns TEXT,
l12_difficult_statement_3_correct_nouns TEXT,
l12_difficult_statement_4_correct_nouns TEXT,
l12_difficult_statement_5_correct_nouns TEXT,
l12_difficult_statement_6_correct_nouns TEXT,
l12_difficult_statement_7_correct_nouns TEXT,
l12_difficult_statement_8_correct_nouns TEXT,
date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP); -->

<!-- CREATE TABLE word_sound_activity_2 (
word_sound_activity_2_ID INT AUTO_INCREMENT PRIMARY KEY,
user_ID INT NOT NULL UNIQUE,
l21_easy_word_1_image mediumblob NOT NULL,
l21_easy_word_2_image mediumblob NOT NULL,
l21_easy_word_3_image mediumblob NOT NULL,
l21_easy_word_4_image mediumblob NOT NULL,
l21_easy_word_5_image mediumblob NOT NULL,
l21_easy_word_6_image mediumblob NOT NULL,
l21_easy_word_7_image mediumblob NOT NULL,
l21_easy_word_8_image mediumblob NOT NULL,
l21_average_word_1_image mediumblob NOT NULL,
l21_average_word_2_image mediumblob NOT NULL,
l21_average_word_3_image mediumblob NOT NULL,
l21_average_word_4_image mediumblob NOT NULL,
l21_average_word_5_image mediumblob NOT NULL,
l21_average_word_6_image mediumblob NOT NULL,
l21_average_word_7_image mediumblob NOT NULL,
l21_average_word_8_image mediumblob NOT NULL,
l21_difficult_word_1_image mediumblob NOT NULL,
l21_difficult_word_2_image mediumblob NOT NULL,
l21_difficult_word_3_image mediumblob NOT NULL,
l21_difficult_word_4_image mediumblob NOT NULL,
l21_difficult_word_5_image mediumblob NOT NULL,
l21_difficult_word_6_image mediumblob NOT NULL,
l21_difficult_word_7_image mediumblob NOT NULL,
l21_difficult_word_8_image mediumblob NOT NULL,
l21_easy_word_1_correct_word TEXT,
l21_easy_word_2_correct_word TEXT,
l21_easy_word_3_correct_word TEXT,
l21_easy_word_4_correct_word TEXT,
l21_easy_word_5_correct_word TEXT,
l21_easy_word_6_correct_word TEXT,
l21_easy_word_7_correct_word TEXT,
l21_easy_word_8_correct_word TEXT,
l21_average_word_1_correct_word TEXT,
l21_average_word_2_correct_word TEXT,
l21_average_word_3_correct_word TEXT,
l21_average_word_4_correct_word TEXT,
l21_average_word_5_correct_word TEXT,
l21_average_word_6_correct_word TEXT,
l21_average_word_7_correct_word TEXT,
l21_average_word_8_correct_word TEXT,
l21_difficult_word_1_correct_word TEXT,
l21_difficult_word_2_correct_word TEXT,
l21_difficult_word_3_correct_word TEXT,
l21_difficult_word_4_correct_word TEXT,
l21_difficult_word_5_correct_word TEXT,
l21_difficult_word_6_correct_word TEXT,
l21_difficult_word_7_correct_word TEXT,
l21_difficult_word_8_correct_word TEXT,
date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP); -->

<!-- CREATE TABLE word_sound_activity_3 (
word_sound_activity_3_ID INT AUTO_INCREMENT PRIMARY KEY,
user_ID INT NOT NULL UNIQUE,
l31_easy_word_1_image mediumblob NOT NULL,
l31_easy_word_2_image mediumblob NOT NULL,
l31_easy_word_3_image mediumblob NOT NULL,
l31_easy_word_4_image mediumblob NOT NULL,
l31_easy_word_5_image mediumblob NOT NULL,
l31_easy_word_6_image mediumblob NOT NULL,
l31_average_word_1_image mediumblob NOT NULL,
l31_average_word_2_image mediumblob NOT NULL,
l31_average_word_3_image mediumblob NOT NULL,
l31_average_word_4_image mediumblob NOT NULL,
l31_average_word_5_image mediumblob NOT NULL,
l31_average_word_6_image mediumblob NOT NULL,
l31_difficult_word_1_image mediumblob NOT NULL,
l31_difficult_word_2_image mediumblob NOT NULL,
l31_difficult_word_3_image mediumblob NOT NULL,
l31_difficult_word_4_image mediumblob NOT NULL,
l31_difficult_word_5_image mediumblob NOT NULL,
l31_difficult_word_6_image mediumblob NOT NULL,
l31_easy_word_1_correct_word TEXT,
l31_easy_word_2_correct_word TEXT,
l31_easy_word_3_correct_word TEXT,
l31_easy_word_4_correct_word TEXT,
l31_easy_word_5_correct_word TEXT,
l31_easy_word_6_correct_word TEXT,
l31_average_word_1_correct_word TEXT,
l31_average_word_2_correct_word TEXT,
l31_average_word_3_correct_word TEXT,
l31_average_word_4_correct_word TEXT,
l31_average_word_5_correct_word TEXT,
l31_average_word_6_correct_word TEXT,
l31_difficult_word_1_correct_word TEXT,
l31_difficult_word_2_correct_word TEXT,
l31_difficult_word_3_correct_word TEXT,
l31_difficult_word_4_correct_word TEXT,
l31_difficult_word_5_correct_word TEXT,
l31_difficult_word_6_correct_word TEXT,
date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP); -->
